### ISSUE TITLE
on voudrait juste les codes + "Ba_ Gateway" ?

### ISSUE THREAD

**Issue by pmagistry** [Karlemami/PPE2023#1]
https://github.com/Karlemami/PPE2023/blame/f99ecb59af24a76bcf38614c192396f37ba4fc40/mini-projet/tableaux/tableau_fr.txt#L6

Les données pourraient être nettoyées (juste les codes comme 200 ou 502 sans le HTTP/)
voir "Ba  gateway" sans le 'd' de "Bad" montre qu'il y a sûrement une petite erreur dans le script.

**Comment by Karlemami** [comment]
C'est réglé; j'ai nettoyé les données HTTP avec un `egrep` pour isoler le code, et les données d'encodage avec un `tr` pour supprimer le "charset=".
